---
#
# Browbeat Install
#

- name: Install python development tools
  yum: name=python-devel state=present
  become: true

- name: Install browbeat matplotlib dependencies
  yum: name={{ item }} state=present
  become: true
  with_items:
    - freetype-devel
    - libpng-devel

- name: Install pip
  easy_install: name=pip
  become: true

- name: Install virtualenv
  pip: name=virtualenv
  become: true

- name: Create browbeat virtualenv
  command: virtualenv "{{ browbeat_venv }}" creates=""{{ browbeat_venv }}""

- name: Create rally virtualenv
  command: virtualenv "{{ rally_venv }}" creates=""{{ rally_venv }}""

- name: Create shaker virtualenv
  command: virtualenv "{{ shaker_venv }}" creates=""{{ shaker_venv }}""

- name: Clone browbeat on undercloud
  git: repo=https://github.com/jtaleric/browbeat.git dest="{{ home_dir }}"/browbeat
  when: "'localhost' not in '{{ inventory_hostname }}'"

- name: Generate hosts and ~/.ssh/config on undercloud
  shell: . "{{ home_dir }}"/stackrc; "{{ home_dir }}"/browbeat/ansible/gen_hostfile.sh localhost "{{ home_dir }}"/.ssh/config
  when: "'localhost' not in '{{ inventory_hostname }}'"

- name: Move hosts file to correct location
  command: mv "{{ home_dir }}"/hosts "{{ home_dir }}"/browbeat/ansible/hosts
  when: "'localhost' not in '{{ inventory_hostname }}'"

- name: Install requirements.txt into browbeat-venv
  pip: requirements="{{ browbeat_path }}"/requirements.txt virtualenv=""{{ browbeat_venv }}""
  become: true

- name: Install rally into rally-venv
  pip: name=rally virtualenv="{{ rally_venv }}"
  become: true

- name: Setup rally database
  shell: . "{{ rally_venv}}"/bin/activate; rally-manage db recreate

- name: Setup rally deployment
  shell: . "{{ rally_venv }}"/bin/activate; . "{{ overcloudrc }}"; rally deployment create --fromenv --name overcloud

- name: Install shaker
  pip: name=pyshaker version=0.0.10 virtualenv=""{{ shaker_venv }}""

- name: Check for shaker port in iptables
  shell: iptables -nvL | grep -q "dpt:"{{ shaker_port }}""
  become: true
  changed_when: false
  register: shaker_iptables
  ignore_errors: true

- name: Open up shaker port in iptables
  shell: /usr/sbin/iptables -I INPUT 1 -p tcp --dport {{ shaker_port }} -j ACCEPT
  become: true
  when: shaker_iptables.rc == 1

#
# Serve results out of httpd if results_in_httpd is set to true
#

- name: Setup browbeat.conf in /etc/httpd/conf.d
  template:
    src: 00-browbeat.conf.j2
    dest: /etc/httpd/conf.d/00-browbeat.conf
    owner: root
    group: root
    mode: 0644
  become: true
  when: results_in_httpd
  notify:
    - restart httpd

- name: Check iptables for browbeat port(9000)
  shell: iptables -nvL | grep -q "dpt:9000"
  become: true
  changed_when: false
  when: results_in_httpd
  register: browbeat_results_port
  ignore_errors: true

- name: Open iptables for browbeat port(9000)
  shell: /usr/sbin/iptables -I INPUT 1 -p tcp --dport 9000 -j ACCEPT
  become: true
  when: results_in_httpd and browbeat_results_port.rc == 1

- name: Set seboolean(httpd_read_user_content)
  seboolean: name=httpd_read_user_content state=yes persistent=yes
  become: true
  when: results_in_httpd

- name: Allow httpd to serve content in "{{ home_dir }}"
  file: path="{{ home_dir }}" state=directory mode=0755
  when: results_in_httpd

#
# Nova boot image tasks
#

- name: Fetch cirros image
  get_url: url={{ cirros_image_url }} dest="{{ home_dir }}"/cirros.img

- name: Determine is cirros image exists
  shell: . "{{ overcloudrc }}"; glance image-list | grep "cirros"
  register: cirros_image_exists
  ignore_errors: true
  changed_when: false

- name: Upload cirros image into cloud (OSP8)
  shell: . "{{ overcloudrc }}"; glance image-create --name cirros --visibility public --disk-format=qcow2 --container-format=bare < "{{ home_dir }}"/cirros.img
  when: "'cirros' not in '{{ cirros_image_exists.stdout }}'"
  register: cirros_image_osp8
  ignore_errors: true

- name: Upload cirros image into cloud (OSP7)
  shell: . "{{ overcloudrc }}"; glance image-create --name cirros --is-public true --disk-format=qcow2 --container-format=bare < "{{ home_dir }}"/cirros.img
  when: "'cirros' not in '{{ cirros_image_exists.stdout }}' and not cirros_image_osp8.rc == 0"
  ignore_errors: true


- name: Fetch centos7 image
  get_url: url={{ centos_image_url }} dest="{{ home_dir }}"/centos7.qcow2

- name: Determine is centos7 image exists
  shell: . "{{ overcloudrc }}"; glance image-list | grep "centos7"
  register: centos7_image_exists
  ignore_errors: true
  changed_when: false

- name: Upload centos7 image into cloud (OSP8)
  shell: . "{{ overcloudrc }}"; glance image-create --name centos7 --visibility public --disk-format=qcow2 --container-format=bare < "{{ home_dir }}"/centos7.qcow2
  when: "'centos7' not in '{{ centos7_image_exists.stdout }}'"
  register: centos7_image_osp8
  ignore_errors: true

- name: Upload centos7 image into cloud (OSP7)
  shell: . "{{ overcloudrc }}"; glance image-create --name centos7 --is-public true --disk-format=qcow2 --container-format=bare < "{{ home_dir }}"/centos7.qcow2
  when: "'centos7' not in '{{ centos7_image_exists.stdout }}' and not centos7_image_osp8.rc == 0"
  ignore_errors: true
