---
- hosts: compute
  remote_user: "{{ host_remote_user }}"
  become: true
  roles:
    - compute

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  become: true
  roles:
    - common
    - nova
    - neutron
    - keystone
    - ceilometer
    - cinder
    - heat
    - mysql
    - rabbitmq

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  become: true
  roles:
    - undercloud

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  roles:
    - dump-facts
