---
#
# Browbeat's PerfKitBenchmarker Install
#

- name: Create perfkit virtualenv
  command: virtualenv {{ perfkit_venv }} creates={{ perfkit_venv }}

- name: Setup perfkit-venv CA certificate path
  lineinfile:
    dest: "{{ perfkit_venv }}/bin/activate"
    line: 'export REQUESTS_CA_BUNDLE={{ overcloud_ca_path }}'
  when: overcloud_ca_path is defined

- name: Determine if PerfKitBenchmarker is already cloned
  stat:
    path: "{{ perfkit_venv }}/PerfKitBenchmarker"
  register: perfkit_exists

- debug: msg="PerfKitBenchmarker already exists on the host"
  when: perfkit_exists.stat.isdir is defined and perfkit_exists.stat.isdir

- name: Clone PerfKitBenchmarker on undercloud
  git:
    repo: https://github.com/GoogleCloudPlatform/PerfKitBenchmarker.git
    dest: "{{perfkit_venv}}/PerfKitBenchmarker"
    version: "{{perfkit_version}}"
  when: perfkit_exists.stat.isdir is undefined

- name: Install PerfKitBenchmarker requirements into perfkit-venv
  pip:
     requirements: "{{perfkit_venv}}/PerfKitBenchmarker/requirements.txt"
     virtualenv: "{{perfkit_venv}}"

- name: Install PerfKitBenchmarker Openstack requirements into perfkit-venv
  pip:
     requirements: "{{ perfkit_venv }}/PerfKitBenchmarker/perfkitbenchmarker/providers/openstack/requirements.txt"
     virtualenv: "{{perfkit_venv}}"

# (akrzos) - Using 2.6 seems most stable, Using latest or >2.6 as per PerfKitBenchmarker
# openstack/requirements.txt results in an openstack cli error.
- name: Downgrade python-openstackclient inside perfkit-venv
  pip:
    name: python-openstackclient
    version: 2.6.0
    virtualenv: "{{perfkit_venv}}"
