---
- name: Get Network ID
  shell: "source {{ ansible_env.HOME }}/overcloudrc; neutron net-list | grep {{ browbeat_pri_net_name }} | cut -f 2 -d'|'"
  register: nova_test_net_name

- name: Template Browbeat configuration
  template:
    "src={{ browbeat_config_file }} \
     dest={{ ansible_env.HOME }}/browbeat/browbeat-config.yaml"
