---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/ansible/ansible-lint
    rev: 49372c5c3822567f36a809b20e0273020f024ed7
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        exclude: ^(rally/|\.zuul\.yaml)
        entry: ansible-lint --force-color -v
