---
#
# Playbook to apply changes to ceilometer.
#
# Examples (backend):
# ansible-playbook -i hosts browbeat/adjustment-ceilometer.yml -e "ceilometer_backend=database"
# ansible-playbook -i hosts browbeat/adjustment-ceilometer.yml -e "ceilometer_backend=gnocchi"
#
# Examples (interval):
# ansible-playbook -i hosts browbeat/adjustment-ceilometer.yml -e "ceilometer_interval=60"
# ansible-playbook -i hosts browbeat/adjustment-ceilometer.yml -e "ceilometer_interval=600"
#

- hosts: controller
  remote_user: heat-admin
  roles:
    - { role: ceilometer-backend, when: ceilometer_backend is defined }

- hosts: controller,compute
  remote_user: heat-admin
  roles:
    - { role: ceilometer-interval, when: ceilometer_interval is defined }
