---
#
# Playbook to change number of workers for nova and keystone services
#

- hosts: controller
  remote_user: heat-admin
  vars:
    keystone_deployment: not_defined
    workers: 24
    threads: 6
  roles:
  - nova
  - keystone
