---
#
# Playbook to change telemetry's polling yaml
#
# Deploy polling.yaml with specific interval:
#
# ansible-playbook -i hosts browbeat/telemetry-polling.yml -e 'polling_interval=600'
#
# Deploy with reduced metrics:
#
# ansible-playbook -i hosts browbeat/telemetry-polling.yml -e 'polling_interval=600 reduced_metrics=true'
#
# Remember to sync polling daemons afterwards (Restarting openstack-ceilometer-[central,compute])
#

- hosts: controller,compute
  remote_user: "{{ host_remote_user }}"
  gather_facts: false
  vars_files:
    - ../install/group_vars/all.yml
  vars:
    polling_interval: 300
    reduced_metrics: false
  roles:
    - ceilometer-polling
