---
#
# Browbeat Install Common
#

- name: Check for DNS record
  command: grep "{{ dns_server }}" /etc/resolv.conf
  register: dns_record
  failed_when: false
  changed_when: false

- name: Add DNS record
  shell: echo "nameserver {{ dns_server }}" | tee -a /etc/resolv.conf
  when: dns_record.rc == 1

- name: Get rhel repo file tfrom director
  fetch: src=/etc/yum.repos.d/rhos-release-rhel-7.2.repo dest=roles/common/files/rhel.repo flat=yes
  when: director
  changed_when: false

- name: Copy rhel repo file to controllers/computes
  copy: src=rhel.repo dest=/etc/yum.repos.d/
  when: not director
