---
#
# Tasks for pbench
#

- name: Install pbench repo file
  get_url: url="{{ pbench_repo_file_url }}" dest=/etc/yum.repos.d/pbench.repo
  when: pbench

- name: Install pbench-agent
  yum: name=pbench-agent state=latest
  when: pbench

- name: Ensure pbench directory exists as stack user on director
  file: path=/var/lib/pbench-agent state=directory owner=stack group=stack recurse=yes
  when: director

- name: Get director stack ssh public key
  fetch: src=/home/stack/.ssh/id_rsa.pub dest=roles/common/files/stack_id_rsa.pub flat=yes
  when: director
  changed_when: false

- name: Unblock root user ssh on controllers/computes
  lineinfile: dest=/root/.ssh/authorized_keys state=absent regexp="Please login as the user" mode=0600
  when: not director

- name: Copy director stack ssh public key to controllers/compute authorized_keys
  lineinfile: dest=/root/.ssh/authorized_keys state=present line="{{ stack_ssh_key }}"
  when: not director
