---
#
# Tasks for pbench
#

- name: Get repo file from director
  fetch: src=/etc/yum.repos.d/"{{ repo_name }}" dest=roles/pbench/files/el.repo flat=yes
  when: pbench and director
  changed_when: false

- name: Copy repo file to controllers/computes
  copy: src=el.repo dest=/etc/yum.repos.d/
  when: pbench and not director

- name: Install pbench repo file
  get_url: url="{{ pbench_repo_file_url }}" dest=/etc/yum.repos.d/pbench.repo
  when: pbench

- name: Install pbench-agent
  yum: name=pbench-agent state=latest
  when: pbench

- name: Ensure pbench directory exists as stack user on director
  file: path=/var/lib/pbench-agent state=directory owner=stack group=stack recurse=yes
  when: director and pbench

- name: Ensure pbench id_rsa is owned by stack
  file: path=/opt/pbench-agent/id_rsa owner=stack group=stack
  when: director and pbench

- name: Get director root ssh public key
  fetch: src=/root/.ssh/id_rsa.pub dest=roles/pbench/files/director_root_id_rsa.pub flat=yes
  when: director and pbench
  changed_when: false

- name: Get director stack ssh public key
  fetch: src=/home/stack/.ssh/id_rsa.pub dest=roles/pbench/files/director_stack_id_rsa.pub flat=yes
  when: director and pbench
  changed_when: false

- name: Unblock root user ssh on controllers/computes
  lineinfile: dest=/root/.ssh/authorized_keys state=absent regexp="Please login as the user" mode=0600
  when: not director and pbench

- name: Copy director root ssh public key to controllers/compute root user's authorized_keys
  lineinfile: dest=/root/.ssh/authorized_keys state=present line="{{ director_root_ssh_key }}"
  when: not director and pbench

- name: Copy director stack ssh public key to controllers/compute root user's authorized_keys
  lineinfile: dest=/root/.ssh/authorized_keys state=present line="{{ director_stack_ssh_key }}"
  when: not director and pbench
