---
#
# Tasks for pbench
#

- name: Install pbench repo file
  get_url: url="{{ pbench_repo_file_url }}" dest=/etc/yum.repos.d/pbench.repo
  when: pbench

- name: Install pbench-agent
  yum: name=pbench-agent state=latest
  when: pbench

- name: Ensure pbench directory exists as stack user on director
  file: path=/var/lib/pbench-agent state=directory owner=stack group=stack recurse=yes
  when: director
