---
#
# Tasks to get nova facts
#

- name: Parse Nova config
  become: true
  shell: python /tmp/openstack-config-parser.py nova /etc/nova/nova.conf /tmp/out.yml

- name: Fetch output
  fetch: src=/tmp/out.yml dest=/tmp/out.yml flat=yes

- name: Load configuration variables
  include_vars: /tmp/out.yml

