---
#
# Connmon Install
#

- name: Install pip
  easy_install: name=pip
  when: connmon

- name: Install connmon
  pip: name=connmon
  when: connmon

#
# Connmon Setup
#

- name: Configure Connmon Host IP Address
  template:
    src=connmon.cfg.j2
    dest=/etc/connmon.cfg
    owner=root
    group=root
    mode=0644
  with_items:
    - ip_address: "{{ connmon_host }}"
  when: connmon
