---
#
# Neutron handlers for browbeat install connmon
#

- name: unmanage neutron-server
  command: pcs resource unmanage neutron-server
  ignore_errors: true

- name: restart neutron-server
  service: name=neutron-server state=restarted

- name: manage neutron-server
  command: pcs resource manage neutron-server
  ignore_errors: true

- name: cleanup neutron-server
  command: pcs resource cleanup neutron-server
  ignore_errors: true
