---
- name: Ensure nova.conf is properly configured
  ini_file:
    dest: /etc/nova/nova.conf
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - { section: DEFAULT, option: verbose, value: False }
    - { section: DEFAULT, option: debug, value: False }
    - { section: DEFAULT, option: ec2_workers, value: "{{ num_workers }}" }
    - { section: DEFAULT, option: osapi_compute_workers, value: "{{ num_workers }}" }
    - { section: DEFAULT, option: workers, value: "{{ num_workers }}" }
    - { section: DEFAULT, option: metadata_workers, value: "{{ num_workers }}" }
    - { section: conductor, option: workers, value: "{{ num_workers }}" }

- name: Unmanage Nova Service from pacemaker
  shell : pcs resource unmanage {{ item }}
  with_items:
    - openstack-nova-conductor
    - opnestack-nova-api
    - openstack-nova-scheduler

- name: Restart Nova services
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-conductor
    - opnestack-nova-api
    - openstack-nova-scheduler

- name: Manage Nova Service from pacemaker
  shell : pcs resource manage {{ item }}
  with_items:
    - openstack-nova-conductor
    - opnestack-nova-api
    - openstack-nova-scheduler
