- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false

- name: check selinux config file
  lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=enforcing

- name: Check tuned profile on controllers
  command: tuned-adm active
  register: tuned_result

- name: Check max_connections
  shell: mysql -e "show status where \`variable_name\` = 'Max_connections';" | grep Max_used_connections | awk '{print $2}'
  register: max_connections_result

- name : Check rabbitmq file descriptors
  shell: rabbitmqctl status | grep file_descriptors -A 3
  register: rabbitmq_fd_result

- debug: msg="{{ tuned_result.stdout}}"
- debug: msg="{{ rabbitmq_fd_result.stdout}}"
- debug: msg="{{ max_connections_result.stdout}}"
