---
#
# Keystone handlers for browbeat install connmon
#

#
# Restart keystone when in httpd
#

- name: restart httpd
  service: name=httpd state=restarted
  when: "'httpd' == '{{ keystone_deployment }}'"

#
# Restart keystone when in eventlet
#

- name: unmanage keystone
  command: pcs resource unmanage openstack-keystone
  when: "'eventlet' == '{{ keystone_deployment }}'"
  ignore_errors: true

- name: restart keystone
  service: name=openstack-keystone state=restarted
  when: "'eventlet' == '{{ keystone_deployment }}'"

- name: manage keystone
  command: pcs resource manage openstack-keystone
  when: "'eventlet' == '{{ keystone_deployment }}'"
  ignore_errors: true

- name: cleanup keystone
  command: pcs resource cleanup openstack-keystone
  when: "'eventlet' == '{{ keystone_deployment }}'"
  ignore_errors: true
