---
#
# Install/run collectd for browbeat (Generic)
#

- name: Import EPEL GPG Key
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state=present

- name: Check for EPEL repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present

- name: Install collectd rpms
  yum: name={{ item }} state=present
  become: true
  with_items: "{{collectd_packages[config_type]}}"


#
# CFME specific configuration steps
#
- name: Copy cfme-http.conf for apache monitoring
  copy:
    src=cfme-http.conf
    dest=/etc/httpd/conf.d/cfme-http.conf
    owner=root
    group=root
    mode=0644
  when: "'cfme' in '{{config_type}}'"
  notify:
    - restart httpd

#
# Satellite6 specific configuration steps
#
- name: Get Candlepin PostgresDB Password
  command: grep "jpa.config.hibernate.connection.password" /etc/candlepin/candlepin.conf
  register: satellite_candlepin_password
  when: "'{{config_type}}' == 'satellite6'"

- name: Get Foreman PostgresDB Password
  shell: grep "password" /etc/foreman/database.yml | awk '{print $2}' | tr -d '"'
  register: satellite_foreman_password
  when: "'{{config_type}}' == 'satellite6'"


#
# OSE specific configuration
#
# - name: Copy ose-metrics.py
#   template:
#     src=ose-metrics.py.j2
#     dest=/usr/local/bin/ose-metrics.py
#     owner=root
#     group=root
#     mode=0755
#   become: true
#   when: "'{{config_type}}' == 'ose'"

# - name: Allow group read to /etc/origin/master/admin.key
#   file: path=/etc/origin/master/admin.key mode=0640
#   when: "'{{config_type}}' == 'ose'"

- name: Configure collectd.conf
  template:
    src={{config_type}}.collectd.conf.j2
    dest=/etc/collectd.conf
    owner=root
    group=root
    mode=0644
  become: true

#
# Configure selinux bits
#
- name: Check for collectd permissive
  shell: semodule -l | grep -q permissive_collectd_t
  become: true
  register: collectd_permissive
  ignore_errors: true
  changed_when: false

# This command is not always found?
- name: Set permissive for collectd
  shell: semanage permissive -a collectd_t
  become: true
  when: collectd_permissive.rc != 0
  ignore_errors: true

#
# Additional policy bits may be needed for exec
#
- name: Collectd policy customization
  copy:
    src=custom-collectd.pp
    dest=/root/custom-collectd.pp
    owner=root
    group=root
    mode=644
  become: true

- name: Check for collectd custom
  shell: semodule -l | grep -q custom-collectd
  become: true
  register: collectd_custom
  ignore_errors: true
  changed_when: false

- name: Set custom policy for collectd
  shell: semodule -i /root/custom-collectd.pp
  become: true
  when: collectd_custom.rc != 0

#
# Start collectd service
#
- name: Setup collectd service
  service: name=collectd state=restarted enabled=true
  become: true

- name: Disable EPEL Repo
  ini_file: dest=/etc/yum.repos.d/epel.repo
    section=epel
    option=enabled
    value=0
