---
#
# Playbook to install Browbeat (Rally + Shaker + PerfKitBenchmarker) on undercloud
#

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  roles:
    - no-sshd-dns
    - shaker-check

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  roles:
    - common
    - browbeat

- hosts: compute
  remote_user: "{{ host_remote_user }}"
  roles:
    - no-sshd-dns
