---
#
# Playbook to install Browbeat (Rally + Shaker) on undercloud
#

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  roles:
    - shaker-check

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  vars:
    results_in_httpd: true
  roles:
    - common
    - browbeat
