---
#
# Playbook to install collectd on undercloud/overcloud
#
# Install on all undercloud/overcloud machines:
# ansible-playbook -i hosts install/collectd-openstack.yml
#
# Or use tags:
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "undercloud"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "controller"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "ceph"
# ansible-playbook -i hosts install/collectd-openstack.yml --tag "compute"
#


- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  vars:
    config_type: undercloud
  roles:
    - { role: common, when: collectd_undercloud }
    - { role: epel, when: collectd_undercloud }
    - { role: collectd-openstack, when: collectd_undercloud }
  tasks:
    - name: Collectd off if not collectd_undercloud
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_undercloud
      ignore_errors: true
  tags: undercloud

- hosts: controller
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: controller
  roles:
    - { role: common, when: collectd_controller }
    - { role: epel, when: collectd_controller }
    - { role: collectd-openstack, when: collectd_controller }
  tasks:
    - name: Collectd off if not collectd_controller
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_controller
      ignore_errors: true
  tags: controller

- hosts: ceph
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: ceph
  roles:
    - { role: common, when: collectd_ceph }
    - { role: epel, when: collectd_ceph }
    - { role: collectd-openstack, when: collectd_ceph }
  tasks:
    - name: Collectd off if not collectd_ceph
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_ceph
      ignore_errors: true
  tags: ceph

- hosts: compute
  remote_user: "{{ host_remote_user }}"
  vars:
    config_type: compute
  roles:
    - { role: common, when: collectd_compute }
    - { role: epel, when: collectd_compute }
    - { role: collectd-openstack, when: collectd_compute }
  tasks:
    - name: Collectd off if not collectd_compute
      service: name=collectd state=stopped enabled=false
      become: true
      when: not collectd_compute
      ignore_errors: true
  tags: compute
