---
#
# Playbook to install connmon on undercloud/overcloud
#
- hosts: undercloud
  remote_user: stack
  vars:
    ansible_become: true
  roles:
  - common
  - collectd

- hosts: controller:compute
  remote_user: heat-admin
  vars:
    ansible_become: true
  roles:
  - common
  - collectd
