---
#
# Generic Playbook to install collectd on generic machine types, use tags to seperate machine type:
#
# Examples:
#
# ansible-playbook -i hosts install/collectd-generic.yml --tags="baremetal"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="guest"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="cfme-all-in-one"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="cfme-vmdb"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="cfme"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="graphite"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="ose"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="satellite6"
# ansible-playbook -i hosts install/collectd-generic.yml --tags="baremetal,guest"
#

- hosts: baremetal
  remote_user: root
  vars:
    config_type: baremetal
  roles:
    - collectd-generic
  tags: baremetal

- hosts: guest
  remote_user: root
  vars:
    config_type: guest
  roles:
    - collectd-generic
  tags: guest

# Cloud Forms Database appliances with Graphite/Grafana
- hosts: cfme-all-in-one
  remote_user: root
  vars:
    config_type: cfme-all-in-one
  roles:
    - collectd-generic
  tags: cfme-all-in-one

# Cloud Forms Database appliances
- hosts: cfme-vmdb
  remote_user: root
  vars:
    config_type: cfme-vmdb
  roles:
    - collectd-generic
  tags: cfme-vmdb

# Cloud Forms Worker appliances
- hosts: cfme
  remote_user: root
  vars:
    config_type: cfme
  roles:
    - collectd-generic
  tags: cfme

- hosts: graphite
  remote_user: root
  vars:
    config_type: graphite
  roles:
    - collectd-generic
  tags: graphite

- hosts: ose
  remote_user: root
  vars:
    config_type: ose
  roles:
    - collectd-generic
  tags: ose

- hosts: satellite6
  remote_user: root
  vars:
    config_type: satellite6
  roles:
    - collectd-generic
  tags: satellite6
