---
#
# Playbook to install connmon on undercloud/overcloud
#

- hosts: undercloud
  remote_user: stack
  vars:
    ansible_become: true
    undercloud: true
  roles:
  - common
  - connmon

- hosts: controller
  remote_user: heat-admin
  vars:
    ansible_become: true
    undercloud: false
  roles:
  - common
  - connmon
  - nova
  - neutron
  - keystone
  - cinder
