---
#
# Playbook to install connmon and pbench on director/overcloud
#

- hosts: controller
  remote_user: heat-admin
  vars:
    connmon: false
    pbench: false
    shaker: false
  roles:
  - connmon
  - nova
  - keystone
  - pbench
  - shaker

- hosts: director
  remote_user: stack
  vars:
    connmon: false
    pbench: false
    shaker: false
  roles:
  - director
  - connmon
  - pbench
