---
#
# Playbook to install connmon and pbench on undercloud/overcloud
#

- hosts: undercloud
  remote_user: stack
  vars:
    connmon: false
    undercloud: true
    pbench: false
    shaker: false
  roles:
  - common
  - undercloud
  - connmon
  - pbench
  - shaker

- hosts: controller
  remote_user: heat-admin
  vars:
    connmon: false
    undercloud: false
    pbench: false
    shaker: false
  roles:
  - common
  - connmon
  - nova
  - keystone
  - neutron
  - pbench
