---
#
# Playbook to install connmon and pbench on director/overcloud
#

- hosts: director
  remote_user: stack
  vars:
    connmon: false
    director: true
    pbench: false
    shaker: false
  roles:
  - common
  - director
  - connmon
  - pbench
  - shaker

- hosts: controller
  remote_user: heat-admin
  vars:
    connmon: false
    director: false
    pbench: false
    shaker: false
    director_root_ssh_key: "{{ lookup('file', 'roles/pbench/files/director_root_id_rsa.pub') }}"
    director_stack_ssh_key: "{{ lookup('file', 'roles/pbench/files/director_stack_id_rsa.pub') }}"
  roles:
  - common
  - connmon
  - nova
  - keystone
  - neutron
  - pbench
