---
#
# Playbook to install pbench on undercloud/overcloud
#

- hosts: undercloud
  remote_user: stack
  gather_facts: false
  vars:
    ansible_become: true
    undercloud: true
  roles:
  - common
  - pbench

- hosts: controller:compute
  remote_user: heat-admin
  gather_facts: false
  vars:
    ansible_become: true
    undercloud: false
    undercloud_root_ssh_key: "{{ lookup('file', 'roles/pbench/files/undercloud_root_id_rsa.pub') }}"
    undercloud_stack_ssh_key: "{{ lookup('file', 'roles/pbench/files/undercloud_stack_id_rsa.pub') }}"
  roles:
  - common
  - pbench
