---
#
# Playbook to setup undercloud for browbeat
#

- hosts: undercloud
  remote_user: stack
  vars:
    undercloud: true
  gather_facts: false
  roles:
  - common
  tasks:
    - name: Fetch centos7 image
      get_url: url={{ centos_image }} dest=/home/stack/centos7.qcow2

    - name: Determine is centos7 image exists
      shell: . /home/stack/overcloudrc; glance image-list | grep "centos7"
      register: centos7_image_exists
      ignore_errors: true
      changed_when: false

    - name: Upload centos7 image into cloud
      shell: . /home/stack/overcloudrc; glance image-create --name centos7 --disk-format=qcow2 --container-format=bare < /home/stack/centos7.qcow2
      when: "'centos7' not in '{{ centos7_image_exists.stdout }}'"

    - name: Get centos7 image id
      shell: . /home/stack/overcloudrc; glance image-list | grep "centos7" | awk '{print $2}'
      register: centos7_image_id
      changed_when: false

    - name: Set centos7 image public
      shell: . /home/stack/overcloudrc; glance image-update --visibility public {{ centos7_image_id.stdout }}
