---
#
# Playbook to build shaker-image
#

- hosts: undercloud
  remote_user: "{{ local_remote_user }}"
  tasks:
    - name: build shaker image
      shell: >
             source {{ overcloudrc }}; source {{ shaker_venv }}/bin/activate;
             shaker-image-builder --flavor-name {{ shaker_flavor }} --image-builder-template
             {{ shaker_image }} --dns-nameservers {{ shaker_dns_nameserver }} --os-region-name {{ shaker_region }}
      become: true
      register: image_result
      failed_when: image_result.rc != 0
