---
#
# Playbook to build shaker-image
#

- hosts: undercloud
  remote_user: stack
  tasks:
    - name: build shaker image
      shell: >
             source /home/stack/overcloudrc; source /home/stack/shaker-venv/bin/activate;
             shaker-image-builder --flavor-name {{ shaker_flavor }} --image-builder-template
             /home/stack/shaker-venv/lib/python2.7/site-packages/shaker/resources/image_builder_templates/centos.yaml
             --os-region-name regionOne
      become: true
      register: image_result
      failed_when: image_result.rc != 0
