---
#
# Performance checks specific to controller hosts
#

- name: Check max_connections
  shell: mysql -e "show variables like 'max_connections';" | grep max_connections | awk '{print $2}'
  register: max_connections_result
  changed_when: no
  failed_when: max_connections_result.stdout|int < mariadb_max_connections
  ignore_errors: True

- name : Check rabbitmq file descriptors
  shell: rabbitmqctl status | grep file_descriptors | awk -F',' '{print $3}' | sed 's/.$//'
  register: rabbitmq_fd_result
  changed_when: no
  failed_when: rabbitmq_fd_result.stdout|int < rabbitmq_fd
  ignore_errors: True

- name : Check rabbitmq for partitions
  shell: rabbitmqctl cluster_status | grep partitions -A 1 | grep -q controller
  register: rabbitmq_partition_result
  changed_when: no
  failed_when: rabbitmq_partition_result.rc == 0
  ignore_errors: True
