---

- name: Run Browbeat
  shell:
    "source {{ ansible_env.HOME }}/browbeat-venv/bin/activate; \
     cd {{ ansible_env.HOME }}/browbeat/; \
     python browbeat.py rally > {{ ansible_env.HOME }}/browbeat/results/browbeat_run.log"
