# Complete set of Glance Benchmarks
browbeat:
  results : results/
  rerun: 1
  cloud_name: openstack
elasticsearch:
  enabled: false
  regather: false
  host: 1.1.1.1
  port: 9200
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
ansible:
  ssh_config: ansible/ssh-config
  hosts: ansible/hosts
  adjust:
    keystone_token: ansible/browbeat/adjustment-keystone-token.yml
    neutron_l3: ansible/browbeat/adjustment-l3.yml
    nova_db: ansible/browbeat/adjustment-db.yml
    workers: ansible/browbeat/adjustment-workers.yml
  metadata: ansible/gather/site.yml
grafana:
  enabled: true
  grafana_ip: 1.1.1.1
  grafana_port: 3000
  dashboards:
    - openstack-general-system-performance
rally:
  enabled: true
  sleep_before: 5
  sleep_after: 5
  plugins:
    - glance-create-boot-delete: rally/rally-plugins/glance-create-boot-delete
  benchmarks:
    - name: glance
      enabled: true
      concurrency:
        - 8
      times: 10
      scenarios:
        - name: create-image-boot-instances
          enabled: true
          image_location: /home/stack/cirros
          instances: 2
          flavor_name: m1.small
          file: rally/glance/create-image-and-boot-instances-cc.yml
        - name: create-and-delete-image
          enabled: true
          image_location: /home/stack/cirros
          flavor_name: m1.small
          file: rally/glance/create-and-delete-image-cc.yml
        - name: create-and-list-image
          enabled: true
          image_location: /home/stack/cirros
          file: rally/glance/create-and-list-image-cc.yml
        - name: list-images
          enabled: true
          file: rally/glance/list-images-cc.yml
