# Complete set of Keystone Stress tests run 3 times over multiple concurrencies with high repetitions(times)
# This testing will take days to complete. (You have been warned)
browbeat:
  results : results/
  rerun: 3
ansible:
  hosts: ansible/hosts
  adjust:
    keystone_token: ansible/browbeat/adjustment-keystone-token.yml
    neutron_l3: ansible/browbeat/adjustment-l3.yml
    nova_db: ansible/browbeat/adjustment-db.yml
    workers: ansible/browbeat/adjustment-workers.yml
  grafana_snapshot: ansible/browbeat/snapshot-general-performance-dashboard.yml
connmon:
  enabled: false
  sudo: true
grafana:
  enabled: false
  cloud_name: openstack
  grafana_ip: 1.1.1.1
  grafana_port: 3000
  dashboards:
    - openstack-general-system-performance
  snapshot:
    enabled: false
    grafana_api_key: (Your API Key Here)
    snapshot_compute: false
rally:
  enabled: true
  sleep_before: 5
  sleep_after: 5
  venv: /home/stack/rally-venv/bin/activate
  benchmarks:
    - name: authenticate
      enabled: true
      concurrency:
        - 64
        - 128
        - 192
        - 256
        - 320
        - 384
        - 448
        - 512
      times: 10000
      scenarios:
        - name: authentic-cinder
          enabled: true
          file: rally/authenticate/validate_cinder-cc.yml
          sla_max_avg_duration: 12
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: authentic-glance
          enabled: true
          file: rally/authenticate/validate_glance-cc.yml
          sla_max_avg_duration: 12
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: authentic-heat
          enabled: true
          file: rally/authenticate/validate_heat-cc.yml
          sla_max_avg_duration: 12
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: authentic-keystone
          enabled: true
          file: rally/authenticate/keystone-cc.yml
          sla_max_avg_duration: 6
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: authentic-monasca
          enabled: false
          file: rally/authenticate/validate_monasca-cc.yml
          sla_max_avg_duration: 12
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: authentic-neutron
          enabled: true
          file: rally/authenticate/validate_neutron-cc.yml
          sla_max_avg_duration: 18
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: authentic-nova
          enabled: true
          file: rally/authenticate/validate_nova-cc.yml
          sla_max_avg_duration: 12
          sla_max_seconds: 30
          sla_max_failure: 0
    - name: keystonebasic
      enabled: true
      concurrency:
        - 128
        - 256
      times: 5000
      scenarios:
        - name: create-user
          enabled: true
          file: rally/keystonebasic/create_user-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-delete-user
          enabled: true
          file: rally/keystonebasic/create_delete_user-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-user-set-enabled-and-delete
          enabled: true
          enabled_flag: true
          file: rally/keystonebasic/create_user_set_enabled_and_delete-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-tenant
          enabled: true
          file: rally/keystonebasic/create_tenant-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-tenant-with-users
          enabled: true
          file: rally/keystonebasic/create_tenant_with_users-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-list-users
          enabled: true
          file: rally/keystonebasic/create_and_list_users-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-list-tenants
          enabled: true
          file: rally/keystonebasic/create_and_list_tenants-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: add-and-remove-user-role
          enabled: true
          file: rally/keystonebasic/add_and_remove_user_role-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-delete-role
          enabled: true
          file: rally/keystonebasic/create_and_delete_role-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-add-and-list-user-roles
          enabled: true
          file: rally/keystonebasic/create_add_and_list_user_roles-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: get-entities
          enabled: true
          file: rally/keystonebasic/get_entities-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-delete-service
          enabled: true
          file: rally/keystonebasic/create_and_delete_service-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-update-and-delete-tenant
          enabled: true
          file: rally/keystonebasic/create_update_and_delete_tenant-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-user-update-password
          enabled: true
          file: rally/keystonebasic/create_user_update_password-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-list-services
          enabled: true
          file: rally/keystonebasic/create_and_list_services-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-list-ec2credentials
          enabled: true
          file: rally/keystonebasic/create_and_list_ec2credentials-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
        - name: create-and-delete-ec2credentials
          enabled: true
          file: rally/keystonebasic/create_and_delete_ec2credentials-cc.yml
          sla_max_seconds: 30
          sla_max_failure: 0
