# Stress test designed for telemetry services (ceilometer, gnocchi) by
# booting persisting xtiny cirros instances. It boots 100 each iteration
# with a concurrency of 20 instances. A total of 1000 instances are
# booted.  View how system resources degrade over each new set of
# instances booted.
browbeat:
  results : results/
  rerun: 1
  cloud_name: openstack
elasticsearch:
  enabled: false
  regather: false
  host: 1.1.1.1
  port: 9200
  regather: true
  metadata_files:
    - name: hardware-metadata
      file: metadata/hardware-metadata.json
    - name: environment-metadata
      file: metadata/environment-metadata.json
    - name: software-metadata
      file: metadata/software-metadata.json
    - name: version
      file: metadata/version.json
ansible:
  ssh_config: ansible/ssh-config
  hosts: ansible/hosts
  adjust:
    keystone_token: ansible/browbeat/adjustment-keystone-token.yml
    neutron_l3: ansible/browbeat/adjustment-l3.yml
    nova_db: ansible/browbeat/adjustment-db.yml
    workers: ansible/browbeat/adjustment-workers.yml
  grafana_snapshot: ansible/browbeat/snapshot-general-performance-dashboard.yml
  metadata: ansible/gather/site.yml
connmon:
  enabled: false
  sudo: true
grafana:
  enabled: false
  grafana_ip: 1.1.1.1
  grafana_port: 3000
  dashboards:
    - openstack-general-system-performance
  snapshot:
    enabled: false
    snapshot_compute: false
rally:
  enabled: true
  sleep_before: 0
  # Sleeps 30 minutes after each iteration to allow for system resources to degrade or
  # display stepped degrading (If the system is hitting saturation or high utilization)
  sleep_after: 1800
  venv: /home/stack/rally-venv/bin/activate
  plugins:
    - nova: rally/rally-plugins/nova
  benchmarks:
    # Boots a total of 1000 instances, 100 at a time with 30minutes between booting storms
    - name: BrowbeatNovaPersist01
      enabled: true
      concurrency:
        - 20
      times: 100
      scenarios:
        - name: nova-boot-100-01
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-02
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-03
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-04
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-05
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-06
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-07
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-08
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-09
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
        - name: nova-boot-100-10
          enabled: true
          image_name: cirros
          flavor_name: m1.xtiny
          file: rally/rally-plugins/nova/nova_boot_persist.yml
