---
#
# Tasks to set rabbitmq facts for controllers
#
  - name : Get rabbitmq file descriptors
    shell: rabbitmqctl status | grep file_descriptors | awk -F',' '{print $3}' | sed 's/.$//'
    register: rabbitmq_desc
    ignore_errors: true

  - name: Set rabbitmq file descriptors
    set_fact:
      openstack_rabbitmq_file_descriptors: "{{ rabbitmq_desc.stdout }}"


