---
#
# Playbook to check OSP install for common performance tuning issues
#

- hosts: controller
  remote_user: heat-admin
  vars:
  roles:
  - common
  - controller
  - keystone

- hosts: compute
  remote_user: heat-admin
  roles:
  - common
  - compute

- hosts: ceph
  remote_user: heat-admin
  roles:
  - common
  - ceph
