---
#
# Keystone tasks for browbeat
# * Change eventlet worker count or httpd process/thread count
# * Change keystone deployed in eventlet or httpd
#

- name: Determine if keystone is deployed in eventlet
  shell: ps afx | grep "[Kk]eystone-all" -c
  register: deployed
  when: keystone_deployment is undefined
  ignore_errors: true
  changed_when: false

- name: Set keystone_deployment variable/fact to httpd
  set_fact: keystone_deployment='httpd'
  when: keystone_deployment is undefined and deployed.stdout|int == 0

- name: Set keystone_deployment variable/fact to eventlet
  set_fact: keystone_deployment='eventlet'
  when: keystone_deployment is undefined

- name: Get keystone admin ip address
  command: crudini --get /etc/keystone/keystone.conf DEFAULT admin_bind_host
  register: admin_ip_addr
  changed_when: false

- name: Get keystone public ip address
  command: crudini --get /etc/keystone/keystone.conf DEFAULT public_bind_host
  register: public_ip_addr
  changed_when: false

#
# Configure keystone eventlet/httpd
#

- name: Configure eventlet workers
  ini_file:
    dest: /etc/keystone/keystone.conf
    mode: 0640
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - { section: DEFAULT, option: public_workers, value: "{{ workers }}" }
    - { section: DEFAULT, option: admin_workers, value: "{{ workers }}" }
    - { section: eventlet_server, option: public_workers, value: "{{ workers }}" }
    - { section: eventlet_server, option: admin_workers, value: "{{ workers }}" }
  when: "'eventlet' in '{{ keystone_deployment }}'"
  notify:
    - pacemaker unmanaged default
    - stop keystone eventlet
    - restart keystone
    - pacemaker managed default
    - cleanup keystone

- name: Unconfigure keystone in httpd if eventlet
  file:
    path: /etc/httpd/conf.d/10-keystone_wsgi_{{ item }}.conf
    state: absent
  with_items:
    - admin
    - main
  when: "'eventlet' in '{{ keystone_deployment }}'"
  notify:
    - restart httpd
    - cleanup httpd

- name: Create keystone in httpd wsgi directory
  file:
    path: /var/www/cgi-bin/keystone
    state: directory
    owner: keystone
    group: keystone
  when: "'httpd' in '{{ keystone_deployment }}'"

- name: Copy keystone in httpd files over
  copy:
    src: keystone_httpd
    dest: /var/www/cgi-bin/keystone/{{ item }}
    owner: keystone
    group: keystone
    mode: 0744
  with_items:
    - admin
    - main
  when: "'httpd' in '{{ keystone_deployment }}'"

- name: Configure httpd processes/threads
  template:
    src=keystone_wsgi.conf.j2
    dest=/etc/httpd/conf.d/10-keystone_wsgi_{{ item.interface }}.conf
    owner=root
    group=root
    mode=0644
  with_items:
    - ip_address: "{{ admin_ip_addr.stdout }}"
      interface: "admin"
      processes: "{{ workers }}"
      port: 35357
      threads: "{{ threads }}"
    - ip_address: "{{ public_ip_addr.stdout }}"
      interface: "main"
      processes: "{{ workers }}"
      port: 5000
      threads: "{{ threads }}"
  when: "'httpd' in '{{ keystone_deployment }}'"
  notify:
    - pacemaker unmanaged default
    - stop keystone eventlet
    - restart httpd

- name: Configure/Unconfigure httpd ports.conf for keystone
  template:
    src=keystone_ports.conf.j2
    dest=/etc/httpd/conf/ports.conf
    owner=root
    group=root
    mode=0644
  with_items:
    - admin_ip_address: "{{ admin_ip_addr.stdout }}"
      public_ip_address: "{{ public_ip_addr.stdout }}"
      deployment: "{{ keystone_deployment }}"
  notify:
    - pacemaker unmanaged default
    - stop keystone eventlet
    - restart keystone
    - pacemaker managed default
    - cleanup keystone
