---
#
# Tasks to install shaker for data plane testing
#

- name: Install python development tools
  yum: name=python-devel state=present
  become: true

- name: Install pip
  become: true
  easy_install: name=pip

- name: Install virtualenv
  become: true
  pip: name=virtualenv

- name: Create virtualenv
  command: virtualenv /home/stack/shaker-venv creates="/home/stack/shaker-venv"

- name: Install shaker
  pip: name=pyshaker version=0.0.10 virtualenv=/home/stack/shaker-venv

- name: Check for shaker port in iptables
  shell: iptables -nvL | grep -q "dpt:"{{ shaker_port }}""
  become: true
  changed_when: false
  register: shaker_iptables
  ignore_errors: true

- name: Open up shaker port in iptables
  shell: /usr/sbin/iptables -I INPUT 1 -p tcp --dport {{ shaker_port }} -j ACCEPT
  become: true
  when: shaker_iptables.rc == 1
