---
#
# Tasks to get heat facts
#

- name: Parse Heat config
  become: true
  shell: python /tmp/openstack-config-parser.py heat /etc/heat/heat.conf /tmp/out.yml

- name: Fetch output
  fetch: src=/tmp/out.yml dest=/tmp/out.yml flat=yes

- name: Load configuration variables
  include_vars: /tmp/out.yml
