---
#
# Nova handlers for browbeat adjustment
#

- name: unmanage nova services
  become: true
  command: pcs resource unmanage {{ item }}
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  ignore_errors: true

- name: restart nova services
  become: true
  service: name={{ item }} state=restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor

- name: manage nova services
  become: true
  command: pcs resource manage {{ item }}
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  ignore_errors: true

- name: cleanup nova services
  become: true
  command: pcs resource cleanup {{ item }}
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  ignore_errors: true
