---
#
# Tasks to get cinder facts
#

- name: Parse Cinder config
  become: true
  shell: python /tmp/openstack-config-parser.py cinder /etc/cinder/cinder.conf /tmp/out.yml

- name: Fetch output
  fetch: src=/tmp/out.yml dest=/tmp/out.yml flat=yes

- name: Load configuration variables
  include_vars: /tmp/out.yml
