---
#
# Nova handlers for browbeat install connmon
#

- name: unmanage nova services
  command: pcs resource unmanage {{ item }}
  become: true
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  ignore_errors: true

- name: restart nova services
  service: name={{ item }} state=restarted
  become: true
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor

- name: manage nova services
  command: pcs resource manage {{ item }}
  become: true
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  ignore_errors: true

- name: cleanup nova services
  command: pcs resource cleanup {{ item }}
  become: true
  with_items:
    - openstack-nova-api
    - openstack-nova-scheduler
    - openstack-nova-conductor
  ignore_errors: true
