---
#
# Tests common to Director/Controller/Compute/Ceph
#

- name: Get selinux mode
  command: getenforce
  changed_when: no
  register: sestatus

- name: Check tuned running on host
  command: tuned-adm active
  register: tuned_result
  changed_when: no
  failed_when: tuned_result.rc == -1
  ignore_errors: True

- name: Check tuned for correct profile on host
  command: tuned-adm active
  register: tuned_stdout
  changed_when: no
  ignore_errors: True

- set_fact:
     tuned_result : "{{ tuned_stdout.stdout }}"

