---
#
# Tasks for Director Host to run BrowBeat with Connmon
#

- name: check iptables
  shell: iptables -nvL | grep -q "dpt:5800"
  changed_when: false
  when: connmon
  register: connmon_port
  ignore_errors: true

- name: open up iptables
  shell: /usr/sbin/iptables -I INPUT 1 -p tcp --dport 5800 -j ACCEPT
  when: connmon and connmon_port.rc == 1
