---
#
# Ceilometer change backend handlers
#

- name: pacemaker default unmanaged
  become: true
  command: pcs property set is-managed-default=false
  when: pacemaker_controlled

- name: restart ceilometer services
  become: true
  service: name={{item}} state=restarted
  with_items:
    - openstack-ceilometer-api
    - openstack-ceilometer-central
    - openstack-ceilometer-collector
    - openstack-ceilometer-notification
  when: pacemaker_controlled

- name: restart gnocchi services
  become: true
  service: name={{item}} state=restarted
  with_items:
    - openstack-gnocchi-metricd
    - openstack-gnocchi-statsd

- name: pacemaker default managed
  become: true
  command: pcs property set is-managed-default=true
  when: pacemaker_controlled

- name: pacemaker cleanup ceilometer
  become: true
  command: pcs resource cleanup {{item}}
  with_items:
    - openstack-ceilometer-api
    - openstack-ceilometer-central
    - openstack-ceilometer-collector
    - openstack-ceilometer-notification
  when: inventory_hostname == groups['controller'][0] and pacemaker_controlled

- name: pacemaker cleanup gnocchi
  become: true
  command: pcs resource cleanup {{item}}
  with_items:
    - openstack-gnocchi-metricd
    - openstack-gnocchi-statsd
  when: inventory_hostname == groups['controller'][0] and pacemaker_controlled
