---
#
# Configure nova.conf tasks
#

- name: (Newton, Ocata, Pike) Configure nova.conf
  become: true
  ini_file:
    dest: "{{nova_config_file}}"
    mode: 0640
    # (akrzos) Commented out Group as to prevent in Pike incorrect permissions on config file
    # group: nova
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - "{{nova_configuration}}"

- name: (Newton, Ocata) Restart Nova Services
  become: true
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-nova-scheduler
    - openstack-nova-api
    - openstack-nova-conductor
    - openstack-nova-novncproxy
    - openstack-nova-consoleauth
    - httpd
  when: "('Newton' in osp_version['content'] | b64decode or 'Ocata' in osp_version['content'] | b64decode) and (restart_nova)"

- name: (Pike) Restart Nova Scheduler Container
  become: true
  command: "docker restart {{item}}"
  with_items:
    - nova_scheduler
  when: "('Pike' in osp_version['content'] | b64decode) and (restart_nova)"
