---
#
# Configure nova.conf tasks
#

- name: Configure nova.conf
  become: true
  ini_file:
    dest: /etc/nova/nova.conf
    mode: 0640
    group: nova
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    backup: yes
  with_items:
    - "{{nova_configuration}}"

- name: Restart Nova Services
  become: true
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-nova-scheduler
    - openstack-nova-api
    - openstack-nova-conductor
    - openstack-nova-novncproxy
    - openstack-nova-consoleauth
    - httpd
  when: restart_nova
