---
#
# Keystone connmon tasks
#

- name: Determine if keystone is deployed in eventlet
  shell: ps afx | grep "[Kk]eystone-all" -c
  register: deployed
  ignore_errors: true
  changed_when: false

- name: Set keystone_deployment variable/fact to httpd
  set_fact: keystone_deployment='httpd'
  when: deployed.stdout|int == 0

- name: Set keystone_deployment variable/fact to eventlet
  set_fact: keystone_deployment='eventlet'
  when: deployed.stdout|int > 0

#
# Configure connmon in keystone.conf
#

- name: Check for connmon in keystone.conf
  shell: grep -Eq 'connection\s?=\s?mysql:' /etc/keystone/keystone.conf
  register: keystone_mysql
  become: true
  ignore_errors: true
  changed_when: false

- name: Enable connmon in keystone.conf
  shell: sed -i 's/mysql:/mysql+connmon:/g' /etc/keystone/keystone.conf
  when: keystone_mysql.rc == 0
  become: true
  notify:
    - restart httpd
    - unmanage keystone
    - restart keystone
    - manage keystone
    - cleanup keystone
