---
#
# Browbeat's Rally Install
#

- name: Create rally virtualenv
  command: virtualenv {{ rally_venv }} creates={{ rally_venv }}

- name: Rally Add browbeat to Python path
  shell: echo 'export PYTHONPATH=$PYTHONPATH:{{ browbeat_path }}' >> {{ rally_venv }}/bin/activate

- name: Setup rally-venv CA certificate path
  lineinfile:
    dest: "{{ rally_venv }}/bin/activate"
    line: 'export REQUESTS_CA_BUNDLE={{ overcloud_ca_path }}'
  when: overcloud_ca_path is defined

- name: Install Rally with OpenStack plugins into rally-venv
  pip:
    name: rally-openstack
    version: "{{ rally_openstack_version }}"
    virtualenv: "{{ rally_venv }}"

- name: Install rally-requirements.txt into rally-venv
  pip:
    requirements: "{{ browbeat_path }}/rally-requirements.txt"
    virtualenv: "{{ rally_venv }}"

- name: Create rally configuration directory
  file:
    path: "{{ rally_venv }}/etc/rally"
    state: directory

- name: Setup rally.conf
  template:
    src: rally.conf.j2
    dest: "{{ rally_venv }}/etc/rally/rally.conf"

- name: Setup rally database
  shell: . {{ rally_venv }}/bin/activate; rally db recreate

- block:
    - name: copy of stackrc
      copy:
        src: "{{ stackrc }}"
        dest: "{{home_dir}}/undercloudrc"

    - name: Get the OS_AUTH_URL value in stackrc
      shell: cat undercloudrc | grep OS_AUTH_URL=
      register: os_auth_url

    - name: Add v3 to OS_AUTH_URL in stackrc
      replace:
        path: "{{home_dir}}/undercloudrc"
        regexp: "{{ os_auth_url.stdout }}"
        replace: '{{ os_auth_url.stdout }}/v3'

    - name: Add OS_CACERT to undercloudrc
      lineinfile:
        path: "{{home_dir}}/undercloudrc"
        insertafter: "export OS_USER"
        line: "export OS_CACERT=/etc/pki/ca-trust/source/anchors/undercloud-cacert.pem"
      when: rhosp_version is version('15.0', '>=')

    - name: Setup rally deployment for undercloud
      shell: . {{ rally_venv }}/bin/activate; . "{{home_dir}}/undercloudrc"; rally deployment create --fromenv --name undercloud

    - name: Check Rally deployment for undercloud
      shell: . {{ rally_venv }}/bin/activate; . "{{home_dir}}/undercloudrc"; rally deployment check
      register: rally_deployment_check_undercloud

    - name: Fail if Rally deployment cannot be verfied on undercloud
      fail:
        msg: "Failed to verify that your deployment is ready to benchmark"
      when: rally_deployment_check_undercloud.rc != 0

  when: rally_undercloud_enabled

- name: Setup rally deployment for overcloud
  shell: . {{ rally_venv }}/bin/activate; . {{ overcloudrc }}; rally deployment create --fromenv --name overcloud

- name: Check Rally deployment for overcloud
  shell: . {{ rally_venv }}/bin/activate; . {{ overcloudrc }}; rally deployment check
  register: rally_deployment_check_overcloud

- name: Fail if Rally deployment cannot be verfied for overcloud
  fail:
    msg: "Failed to verify that your deployment is ready to benchmark"
  when: rally_deployment_check_overcloud.rc != 0

