---
#
# Install/run grafana-server for browbeat
#

- name: Check for epel
  shell: rpm -qa | grep -q epel-release
  ignore_errors: true
  register: epel_installed

- name: Install epel repo
  command: rpm -ivh {{ epel_repo }}
  become: true
  when: epel_installed.rc != 0

- name: Install grafana rpms
  yum: name={{ item }} state=present
  become: true
  with_items:
    - https://grafanarel.s3.amazonaws.com/builds/grafana-2.6.0-1.x86_64.rpm

# disable firewalld (might need to create specific firewall rules or leave it to admin to do via iptables)

- name: disable firewalld
  service: name=firewalld state=stopped enabled=false
  become: true

#
# setup the grafana-server service
#

- name: Setup grafana-server service
  service: name=grafana-server state=started enabled=true
  become: true

