---

- name: Make sure dependencies ar installed
  package: name={{item}} state=present
  become: true
  with_items: "{{ browbeat_dependencies }}"

- name: Copy browbeat to the undercloud
  synchronize: "src={{ local_working_dir }}/browbeat dest={{ ansible_env.HOME }}/ use_ssh_args=yes"

- name: Set hosts gen as executable
  shell: "chmod +x {{ ansible_env.HOME }}/browbeat/ansible/generate_tripleo_hostfile.sh"

- name: Fetch Browbeat vars file
  fetch:
    "src={{ ansible_env.HOME }}/browbeat/ansible/install/group_vars/all.yml \
     dest=/tmp/all.yml \
     flat=yes"

- name: Load Browbeat vars
  include_vars: /tmp/all.yml