---

- name: Copy bash file
  copy:
    src: uuid_extract.sh
    dest: /tmp

- name: Parse uuid from variable
  shell: "sh /tmp/uuid_extract.sh {{ ansible_env.HOME }}/browbeat/log/debug.log"
  register: browbeat_uuid

- name: Clone and Install Browbeat-ML dependencies
  pip:
    name: "git+https://github.com/jkilpatr/Browbeat-ML#egg=bml"
    virtualenv: "{{ ansible_env.HOME }}/browbeat-venv"

- name: Run Browbeat-ML on uuid
  shell: "source {{ ansible_env.HOME }}/browbeat-venv/bin/activate; bml --summary-uuid {{browbeat_uuid.stdout}} --update-db True "
  register: browbeatml_summary

- debug: msg="{{ browbeatml_summary.stdout_lines }}"



