---
collectd_logs:
    undercloud:
       - log_path: /var/log/nova/nova-api.log
         instance: nova-api
       - log_path: /var/log/nova/nova-compute.log
         instance: nova-compute
       - log_path: /var/log/nova/nova-conductor.log
         instance: nova-conductor
       - log_path: /var/log/nova/nova-scheduler.log
         instance: nova-scheduler
       - log_path: /var/log/glance/api.log
         instance: glance-api
       - log_path: /var/log/heat/heat-engine.log
         instance: heat-engine
       - log_path: /var/log/heat/heat_api.log
         instance: heat-api
       - log_path: /var/log/ironic/ironic-conductor.log
         instance: ironic-conductor
       - log_path: /var/log/ironic-inspector/ironic-inspector.log
         instance: ironic-inspector
       - log_path: /var/log/keystone/keystone.log
         instance: keystone
       - log_path: /var/log/mistral/api.log
         instance: mistral-api
       - log_path: /var/log/mistral/engine.log
         instance: mistral-engine
       - log_path: /var/log/mistral/event-engine.log
         instance: mistral-event-engine
       - log_path: /var/log/mistral/executor.log
         instance: mistral-executor
       - log_path: /var/log/mariadb/mariadb.log
         instance: mysql
       - log_path: /var/log/containers/neutron/dhcp-agent.log
         instance: neutron-dhcp-agent
       - log_path: /var/log/neutron/ironic-neutron-agent.log
         instance: neutron-ironic-agent
       - log_path: /var/log/neutron/l3-agent.log
         instance: neutron-l3-agent
       - log_path: /var/log/neutron/openvswitch-agent.log
         instance: neutron-openvswitch-agent
       - log_path: /var/log//neutron/server.log
         instance: neutron-server
       - log_path: /var/log/nova/nova-placement-api.log
         instance: nova-plancement
       - log_path: /var/log/zaqar/zaqar-server.log
         instance: zaqar-server
       - log_path: /var/log/httpd/heat_api_wsgi_error.log
         instance: heat-api-wsgi
       - log_path: /var/log/httpd/ironic_wsgi_error.log
         instance: ironic-api-wsgi
       - log_path: /var/log/httpd/ipxe_vhost_error.log
         instance: ironic-pxe-wsgi
       - log_path: /var/log/httpd/keystone_wsgi_error.log
         instance: keystone-wsgi
       - log_path: /var/log/httpd/nova_api_wsgi_error.log
         instance: nova-api-wsgi
       - log_path: /var/log/httpd/placement_wsgi_error.log
         instance: nova-placement-wsgi
       - log_path: /var/log/httpd/zaqar_wsgi_error.log
         instance: zaqar-api-wsgi
    controller:
        - log_path: /var/log/containers/aodh/aodh-evaluator.log
          instance: aodh-evaluator
        - log_path: /var/log/containers/aodh/aodh-listener.log
          instance: aodh-listener
        - log_path: /var/log/containers/aodh/aodh-notifier.log
          instance: aodh-notifier
        - log_path: /var/log/containers/ceilometer/agent-notification.log
          instance: ceilometer-agent-notification
        - log_path: /var/log/containers/ceilometer/central.log
          instance: ceilometer-central
        - log_path: /var/log/containers/cinder/cinder-api.log
          instance: cinder-api
        - log_path: /var/log/containers/cinder/cinder-scheduler.log
          instance: cinder-scheduler
        - log_path: /var/log/containers/cinder/cinder-volume.log
          instance: cinder-volume
        - log_path: /var/log/containers/glance/api.log
          instance: glance-api
        - log_path: /var/log/containers/gnocchi/gnocchi-metricd.log
          instance: gnocchi-metricd
        - log_path: /var/log/containers/gnocchi/gnocchi-statsd.log
          instance: gnocchi-statsd
        - log_path: /var/log/containers/heat/heat_api_cfn.log
          instance: heat-api-cfn
        - log_path: /var/log/containers/heat/heat_api.log
          instance: heat-api
        - log_path: /var/log/containers/heat/heat-engine.log
          instance: heat-engine
        - log_path: /var/log/containers/keystone/keystone.log
          instance: keystone
        - log_path: /var/log/containers/mysql/mariadb.log
          instance: mysql
        - log_path: /var/log/containers/neutron/server.log
          instance: neutron-server
        - log_path: /var/log/containers/neutron/l3-agent.log
          instance: neutron-l3-agent
        - log_path: /var/log/containers/neutron/dhcp-agent.log
          instance: neutron-dhcp-agent
        - log_path: /var/log/containers/neutron/metadata-agent.log
          instance: neutron-metadata-agent
        - log_path: /var/log/containers/neutron/openvswitch-agent.log
          instance: neutron-openvswitch-agent
        - log_path: /var/log/containers/nova/nova-api.log
          instance: nova-api
        - log_path: /var/log/containers/nova/nova-conductor.log
          instance: nova-conductor
        - log_path: /var/log/containers/nova/nova-scheduler.log
          instance: nova-scheduler
        - log_path: /var/log/containers/nova/nova-metadata-api.log
          instance: nova-metadata-api
        - log_path: /var/log/containers/nova/nova-novncproxy.log
          instance: nova-novncproxy
        - log_path: /var/log/containers/openvswitch/ovn-controller.log
          instance: ovn-controller
        - log_path: /var/log/containers/openvswitch/ovn-northd.log
          instance: ovn-northd
        - log_path: /var/log/containers/openvswitch/ovsdb-server-nb.log
          instance: ovsdb-server-nb
        - log_path: /var/log/containers/openvswitch/ovsdb-server-sb.log
          instance: ovsdb-server-sb
        - log_path: /var/log/containers/nova/nova-placement-api.log
          instance: nova-placement
        - log_path: /var/log/containers/rabbitmq/rabbit@{{ inventory_hostname }}.log
          instance: rabbitmq-server
        - log_path: /var/log/containers/redis/redis.log
          instance: redis-server
        - log_path: /var/log/containers/httpd/heat-api/heat_api_wsgi_error.log
          instance: heat-api-wsgi
        - log_path: /var/log/containers/httpd/ironic-api/ironic_wsgi_error.log
          instance: ironic-api-wsgi
        - log_path: /var/log/containers/httpd/ironic-pxe/ipxe_vhost_error.log
          instance: ironic-pxe-wsgi
        - log_path: /var/log/containers/httpd/keystone/keystone_wsgi_error.log
          instance: keystone-wsgi
        - log_path: /var/log/containers/httpd/nova-api/nova_api_wsgi_error.log
          instance: nova-api-wsgi
        - log_path: /var/log/containers/httpd/nova-placement/placement_wsgi_access.log
          instance: nova-placement-wsgi
        - log_path: /var/log/containers/httpd/zaqar/zaqar_wsgi_error.log
          instance: zaqar-api-wsgi
        - log_path: /var/log/containers/httpd/aodh-api/aodh_wsgi_error.log
          instance: aodh-api-wsgi
        - log_path: /var/log/containers/httpd/cinder-api/cinder_wsgi_error.log
          instance: cinder-api-wsgi
        - log_path: /var/log/containers/httpd/gnocchi-api/gnocchi_wsgi_error.log
          instance: gnocchi-api-wsgi
        - log_path: /var/log/containers/httpd/heat-api-cfn/heat_api_cfn_wsgi_error.log
          instance: heat-api-cfn-wsgi
        - log_path: /var/log/containers/httpd/nova-metadata/nova_metadata_wsgi_error.log
          instance: nova-metadata-wsgi
        - log_path: /var/log/containers/httpd/octavia-api/octavia_wsgi_error.log
          instance: octavia-api
        - log_path: /var/log/containers/swift/swift.log
          instance: swift
    compute:
        - log_path: /var/log/containers/libvirt/libvirtd.log
          instance: ilbvirtd
        - log_path: /var/log/containers/neutron/l3-agent.log
          instance: neutron-l3-agent
        - log_path: /var/log/containers/neutron/metadata-agent.log
          instance: neutron-metadata-agent
        - log_path: /var/log/containers/neutron/openvswitch-agent.log
          instance: neutron-openvswitch-agent
        - log_path: /var/log/containers/neutron/ovn-metadata-agent.log
          instance: ovn-metadata-agent
        - log_path: /var/log/containers/nova/nova-compute.log
          instance: nova-compute
        - log_path: /var/log/containers/openvswitch/ovn-controller.log
          instance: ovn-controller
